FROM innersource-artefacts-docker.optum.cloud/ingested/confluentinc/confluent-init-container:3.2.0
LABEL workstream="Continuous Streaming Service - KAFMRSC (Kafka multi-region stretched cluster)" \
      maintainer="Harish" \
      email="gcpgkekafka@gmail.com" \
      cmdb_appid="AL12345"