FROM innersource-artefacts-docker.optum.cloud/ingested/confluentinc/confluent-operator:0.1514.1
LABEL workstream="Continuous Streaming Service - KAFMRSC (Kafka multi-region stretched cluster)" \
      maintainer="Harish" \
      email="gcpgkekafka@gmail.com" \
      cmdb_appid="AL12345"


FROM confluentinc/confluent-operator:0.1514.40
LABEL workstream="Continuous Streaming Service - KAFMRSC (Kafka multi-region stretched cluster)" \
      maintainer="Harish" \
      email="gcpgkekafka@gmail.com" \
      cmdb_appid="AL12345"
